version: '3.8'

services:
  spark-master:
    container_name: spark-master
    build:
      context: .
    image: spark-image
    entrypoint: [ './entrypoint.sh', 'master' ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - spark-logs:/opt/spark/spark-events
    environment:
      - SPARK_NO_DAEMONIZE=true
    env_file: spark.env
    ports:
      - '9090:8080'
      - '7077:7077'
      - '4040:4040'

  spark-worker-1:
    image: spark-image
    container_name: spark-worker-1
    entrypoint: ['./entrypoint.sh', 'worker', '8081']
    depends_on:
      - spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1g

  spark-worker-2:
    image: spark-image
    container_name: spark-worker-2
    entrypoint: ['./entrypoint.sh', 'worker', '8082']
    depends_on:
      - spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1g

  spark-worker-3:
    image: spark-image
    container_name: spark-worker-3
    entrypoint: ['./entrypoint.sh', 'worker', '8083']
    depends_on:
      - spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./apps:/opt/spark/work-dir/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1g

  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: [ './entrypoint.sh', 'history' ]
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

volumes:
  spark-logs:
